import type { Metadata } from 'next'
import {
  Geist,
  Geist_Mono,
  Roboto,
  Noto_Serif,
  Lato,
  Open_Sans,
  Playfair_Display,
  JetBrains_Mono,
} from 'next/font/google'
import { StackProvider, StackTheme } from '@stackframe/stack'
import { stackServerApp } from '@/stack/server'
import { isStackAuthReady } from '@/lib/env'
import { Suspense } from 'react'
import { TooltipProvider } from '@radix-ui/react-tooltip'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import { Analytics } from '@vercel/analytics/react'
import SiteHeaderServer from '@/components/app/SiteHeaderServer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// Resume Fonts
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

const notoSerif = Noto_Serif({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-noto-serif',
})

const lato = Lato({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-lato',
})

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
})

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// 定义主题配置
const theme = {
  light: {
    primary: '#0EA5E9',
    background: '#ffffff',
    foreground: '#171717',
  },
  dark: {
    primary: '#22C55E',
    background: '#0a0a0a',
    foreground: '#ededed',
  },
  radius: '8px',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${roboto.variable}
          ${notoSerif.variable}
          ${lato.variable}
          ${openSans.variable}
          ${playfair.variable}
          ${jetbrainsMono.variable}
          antialiased
        `}
      >
        {isStackAuthReady() ? (
          <StackProvider app={stackServerApp}>
            <StackTheme theme={theme}>
              <TooltipProvider>
                <Suspense fallback={<div>Loading...</div>}>
                  <SiteHeaderServer />
                  {children}
                </Suspense>
                <Toaster />
                <Analytics />
              </TooltipProvider>
            </StackTheme>
          </StackProvider>
        ) : (
          <TooltipProvider>
            <Suspense fallback={<div>Loading...</div>}>
              <SiteHeaderServer />
              {children}
            </Suspense>
            <Toaster />
            <Analytics />
          </TooltipProvider>
        )}
      </body>
    </html>
  )
}
