import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "@/stack/server";
import { isStackAuthReady } from "@/lib/env";
import { Suspense } from "react";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 定义主题配置
const theme = {
  light: { 
    primary: '#0EA5E9',
    background: '#ffffff',
    foreground: '#171717'
  },
  dark: { 
    primary: '#22C55E',
    background: '#0a0a0a',
    foreground: '#ededed'
  },
  radius: '8px',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isStackAuthReady() ? (
          <StackProvider app={stackServerApp}>
            <StackTheme theme={theme}>
              <TooltipProvider>
                <Suspense fallback={<div>Loading...</div>}>
                  {children}
                </Suspense>
              </TooltipProvider>
            </StackTheme>
          </StackProvider>
        ) : (
          <TooltipProvider>
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
          </TooltipProvider>
        )}
      </body>
    </html>
  );
}
